# Generated by Django 5.1.2 on 2026-03-22 10:46

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0003_remove_hospitaldepartment_available_beds_and_more'),
        ('patients', '0008_patientappointment_hospital_alter_patient_hospital_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('report_name', models.CharField(help_text='Name/title of the medical report', max_length=200)),
                ('report_file', models.FileField(help_text='Uploaded medical report file (PDF, images, etc.)', upload_to='medical_reports/')),
                ('description', models.TextField(blank=True, help_text='Description of the medical report')),
                ('patient', models.ForeignKey(help_text='Patient associated with this medical report', on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patients.patient')),
                ('primary_hospital', models.OneToOneField(help_text='Hospital associated with this medical report', on_delete=django.db.models.deletion.PROTECT, related_name='medical_report', to='hospitals.hospital')),
                ('shared_with', models.ManyToManyField(blank=True, help_text='Hospitals this medical report is shared with', related_name='shared_medical_reports', to='hospitals.hospital')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the medical report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['patient'], name='medical_rep_patient_b3aad0_idx'), models.Index(fields=['primary_hospital'], name='medical_rep_primary_54df63_idx'), models.Index(fields=['uploaded_by'], name='medical_rep_uploade_ab2c42_idx')],
            },
        ),
    ]
