# Generated by Django 5.1.2 on 2026-04-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        ('medical_report', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(help_text='Patient associated with this medical report', on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='primary_hospital',
            field=models.OneToOneField(help_text='Hospital associated with this medical report', on_delete=django.db.models.deletion.PROTECT, related_name='medical_report', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Hospitals this medical report is shared with', related_name='shared_medical_reports', to='hospitals.hospital'),
        ),
    ]
