# Generated by Django 5.1.2 on 2026-04-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_report', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the medical report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['patient'], name='medical_rep_patient_b3aad0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['primary_hospital'], name='medical_rep_primary_54df63_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['uploaded_by'], name='medical_rep_uploade_ab2c42_idx'),
        ),
    ]
