# Generated by Django 5.1.2 on 2026-04-14 11:22

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report_file',
            field=cloudinary.models.CloudinaryField(help_text='Primary medical report image', max_length=255, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='MedicalReportPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('page_number', models.PositiveIntegerField()),
                ('page_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('medical_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='medical_report.medicalreport')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('medical_report', 'page_number')},
            },
        ),
    ]
