# Generated by Django 5.1.2 on 2026-04-10 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_khalti_public_key_and_more'),
        ('medical_report', '0004_alter_medicalreport_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='primary_hospital',
            field=models.ForeignKey(help_text='Hospital associated with this medical report', on_delete=django.db.models.deletion.PROTECT, related_name='medical_reports', to='hospitals.hospital'),
        ),
    ]
