# Generated by Django 5.1.2 on 2026-04-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_report', '0004_alter_medicalreport_report_file_medicalreportpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalReportPage',
        ),
    ]
