# Generated by Django 5.1.2 on 2026-04-14 06:40

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to collect', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online')], default='CASH', help_text='Payment mode used by patient', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(help_text='Appointment linked to this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='patients.patientappointment')),
            ],
            options={
                'verbose_name': 'Appointment Payment',
                'verbose_name_plural': 'Appointment Payments',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['status'], name='payments_ap_status_09a1ab_idx'), models.Index(fields=['payment_method'], name='payments_ap_payment_2ece6f_idx')],
            },
        ),
    ]
