# Generated by Django 6.0 on 2026-03-19 11:21

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentpayment',
            new_name='payments_ap_status_09a1ab_idx',
            old_name='payments_app_status_0af64f_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentpayment',
            new_name='payments_ap_payment_2ece6f_idx',
            old_name='payments_app_payment_360d68_idx',
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='appointmentpayment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ONLINE', 'Online')], default='CASH', help_text='Payment mode used by patient', max_length=20),
        ),
    ]
