# Generated by Django 6.0 on 2026-03-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_payments_app_status_0af64f_idx_payments_ap_status_09a1ab_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpayment',
            name='appointment',
            field=models.OneToOneField(help_text='Appointment linked to this payment', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='patients.patientappointment'),
        ),
    ]
