# Generated by Django 5.1.2 on 2026-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('STAFF', 'Staff'), ('LAB_ASSISTANT', 'Lab Technician'), ('PHARMACIST', 'Pharmacist')], default='PATIENT', help_text='Type of user in the healthcare system', max_length=20),
        ),
    ]
