# Generated by Django 5.1.2 on 2026-03-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user is logging in for the first time",
            ),
        ),
    ]
