# Generated by Django 6.0 on 2026-03-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_first_login",
            new_name="is_default_password",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_default_password",
            field=models.BooleanField(
                default=True,
                help_text="Indicates whether the user is still using the default password",
            ),
        ),
    ]
