# Generated by Django 6.0 on 2026-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_is_first_login_user_is_default_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_removed',
        ),
    ]
