# Generated by Django 5.1.2 on 2026-04-14 06:40

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('expires_at', models.DateTimeField(help_text='Expiration time for the OTP')),
                ('verified', models.BooleanField(default=False, help_text='Whether the OTP has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when OTP was verified', null=True)),
                ('attempts', models.IntegerField(default=0, help_text='Number of verification attempts')),
                ('send_count', models.PositiveSmallIntegerField(default=0, help_text='Number of OTP emails sent in current 24-hour window')),
                ('send_window_started_at', models.DateTimeField(blank=True, help_text='Start time of current 24-hour OTP send window', null=True)),
            ],
            options={
                'verbose_name': 'One Time Password',
                'verbose_name_plural': 'One Time Passwords',
                'ordering': ['-created'],
            },
        ),
    ]
