# Generated by Django 6.0 on 2026-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_removed',
        ),
    ]
