# Generated by Django 5.1.2 on 2026-04-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='send_count',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Number of OTP emails sent in current 24-hour window',
            ),
        ),
        migrations.AddField(
            model_name='otp',
            name='send_window_started_at',
            field=models.DateTimeField(
                blank=True,
                help_text='Start time of current 24-hour OTP send window',
                null=True,
            ),
        ),
    ]
