# Generated by Django 5.1.2 on 2026-03-18 13:02

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_date', models.DateField(help_text='Appointment date')),
                ('appointment_time', models.TimeField(help_text='Appointment time')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled')], default='SCHEDULED', help_text='Appointment status', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for appointment', null=True)),
                ('notes', models.TextField(blank=True, help_text='Doctor notes', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='Cancellation timestamp', null=True)),
                ('cancelled_reason', models.CharField(blank=True, help_text='Cancellation reason', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Patient Appointment',
                'verbose_name_plural': 'Patient Appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender', max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], help_text='Blood group', max_length=5, null=True)),
                ('contact_number', models.CharField(help_text='Contact number', max_length=15)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=100, null=True)),
                ('address', models.TextField(help_text='Residential address')),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Nepal', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Medical history and allergies', null=True)),
                ('insurance_provider', models.CharField(blank=True, help_text='Insurance provider name', max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, help_text='Insurance policy number', max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='patients/profiles/')),
                ('is_verified', models.BooleanField(default=False, help_text='Email verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Verification timestamp', null=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Primary doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['user__first_name'],
            },
        ),
    ]
