# Generated by Django 5.1.2 on 2026-04-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_initial'),
        ('hospitals', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(help_text='User account for this patient', limit_choices_to={'user_type': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital associated with this patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(help_text='Patient', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_verified'], name='patients_pa_is_veri_632154_idx'),
        ),
        migrations.AddIndex(
            model_name='patientappointment',
            index=models.Index(fields=['patient', 'doctor', 'appointment_date'], name='patients_pa_patient_d16917_idx'),
        ),
        migrations.AddIndex(
            model_name='patientappointment',
            index=models.Index(fields=['status'], name='patients_pa_status_2affb2_idx'),
        ),
    ]
