# Generated by Django 6.0 on 2026-03-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_is_removed_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_hospita_4d7fd1_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='hospital',
        ),
    ]
