# Generated by Django 6.0 on 2026-03-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_doctor__f772ca_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
    ]
