# Generated by Django 5.1.2 on 2026-04-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='is_follow_up',
            field=models.BooleanField(default=False, help_text='Is this appointment a follow-up?'),
        ),
    ]
