# Generated by Django 6.0 on 2026-03-19 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_remove_hospitaldepartment_available_beds_and_more'),
        ('patients', '0003_remove_patient_patients_pa_doctor__f772ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='booking_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique booking identifier', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital associated with this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='hospitals.hospital'),
        ),
    ]
