# Generated by Django 6.0 on 2026-03-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_hospital_and_booking_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='booking_uuid',
            field=models.CharField(blank=True, editable=False, help_text='Unique booking code for booking flow', max_length=20, null=True, unique=True),
        ),
    ]
