# Generated by Django 6.0 on 2026-03-19 00:20

from django.db import migrations, models
from django.utils.crypto import get_random_string


def generate_booking_code(prefix='BK'):
    return f"{prefix}{get_random_string(10, allowed_chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789')}"


def backfill_booking_codes(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')

    for patient in Patient.objects.filter(booking_uuid__isnull=True):
        code = generate_booking_code()
        while Patient.objects.filter(booking_uuid=code).exists():
            code = generate_booking_code()
        patient.booking_uuid = code
        patient.save(update_fields=['booking_uuid'])

    for patient in Patient.objects.filter(booking_uuid=''):
        code = generate_booking_code()
        while Patient.objects.filter(booking_uuid=code).exists():
            code = generate_booking_code()
        patient.booking_uuid = code
        patient.save(update_fields=['booking_uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_booking_uuid'),
    ]

    operations = [
        migrations.RunPython(backfill_booking_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='patient',
            name='booking_uuid',
            field=models.CharField(default=generate_booking_code, editable=False, help_text='Unique booking code for booking flow', max_length=20, unique=True),
        ),
    ]
