# Generated by Django 5.1.2 on 2026-03-19 11:31

import apps.patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_booking_code_autogenerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='booking_uuid',
            field=models.CharField(default=apps.patients.models.generate_booking_code, editable=False, help_text='Unique booking code for booking flow', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('FOLLOW_UP', 'Follow-up')], default='SCHEDULED', help_text='Appointment status', max_length=20),
        ),
    ]
