# Generated by Django 6.0 on 2026-03-22 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorschedule_time_slots'),
        ('hospitals', '0003_remove_hospitaldepartment_available_beds_and_more'),
        ('patients', '0007_alter_patient_booking_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientappointment',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital associated with this patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointments', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital associated with this patient', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='doctor',
            field=models.ForeignKey(help_text='Doctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_appointments', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patientappointment',
            name='patient',
            field=models.ForeignKey(help_text='Patient', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient'),
        ),
    ]
