# Generated by Django 5.1.2 on 2026-01-11 07:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Specialization name (e.g., Cardiology, Pediatrics)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Specialization code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of specialization', null=True)),
            ],
            options={
                'verbose_name': 'Specialization',
                'verbose_name_plural': 'Specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(help_text='Medical license number', max_length=50, unique=True)),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=50, unique=True)),
                ('qualification', models.CharField(help_text='Medical qualifications (e.g., MBBS, MD)', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('bio', models.TextField(blank=True, help_text="Doctor's biography", null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee', max_digits=10)),
                ('profile_picture', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='doctors/profiles/')),
                ('is_available', models.BooleanField(default=True, help_text='Currently accepting appointments')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by hospital admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Verification timestamp', null=True)),
                ('joining_date', models.DateField(help_text='Date joined hospital')),
                ('department', models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.hospitaldepartment')),
                ('hospital', models.ForeignKey(help_text='Primary hospital', on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='hospitals.hospital')),
                ('user', models.OneToOneField(help_text='User account for this doctor', limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL)),
                ('additional_specializations', models.ManyToManyField(blank=True, help_text='Additional specializations', related_name='doctors_additional', to='doctors.specialization')),
                ('specialization', models.ForeignKey(help_text='Primary specialization', on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialization')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('slot_duration', models.IntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('max_patients', models.IntegerField(default=20, help_text='Maximum patients per session')),
                ('is_available', models.BooleanField(default=True, help_text='Is schedule active')),
                ('doctor', models.ForeignKey(help_text='Doctor', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['weekday', 'start_time'],
                'unique_together': {('doctor', 'weekday', 'start_time')},
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['hospital', 'specialization'], name='doctors_doc_hospita_a2834b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available', 'is_verified'], name='doctors_doc_is_avai_0215a4_idx'),
        ),
    ]
