# Generated by Django 5.1.2 on 2026-04-14 06:40

import cloudinary.models
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('specialization', models.CharField(help_text='Primary specialization (e.g., Cardiology, Pediatrics)', max_length=100)),
                ('license_number', models.CharField(help_text='Medical license number', max_length=50, unique=True)),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=50, unique=True)),
                ('qualification', models.CharField(help_text='Medical qualifications (e.g., MBBS, MD)', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('bio', models.TextField(blank=True, help_text="Doctor's biography", null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, help_text='Consultation fee', max_digits=10)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('is_available', models.BooleanField(default=True, help_text='Currently accepting appointments')),
                ('joining_date', models.DateField(help_text='Date joined hospital')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week')),
                ('start_time', models.TimeField(help_text='Start time')),
                ('end_time', models.TimeField(help_text='End time')),
                ('slot_duration', models.IntegerField(default=30, help_text='Appointment slot duration in minutes')),
                ('time_slots', models.JSONField(blank=True, default=list, help_text='Auto-calculated appointment time slots')),
                ('max_patients', models.IntegerField(default=20, help_text='Maximum patients per session')),
                ('is_available', models.BooleanField(default=True, help_text='Is schedule active')),
            ],
            options={
                'verbose_name': 'Doctor Schedule',
                'verbose_name_plural': 'Doctor Schedules',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
