# Generated by Django 5.1.2 on 2026-04-01 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='hospitals.hospitaldepartment'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(help_text='Primary hospital', on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='hospitals.hospital'),
        ),
    ]
