# Generated by Django 6.0 on 2026-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='is_removed',
        ),
    ]
