# Generated by Django 5.1.2 on 2026-03-18 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_initial'),
        ('hospitals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(help_text='Primary specialization (e.g., Cardiology, Pediatrics)', max_length=100),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='additional_specializations',
        ),
        migrations.RemoveIndex(
            model_name='doctor',
            name='doctors_doc_is_avai_0215a4_idx',
        ),
        migrations.RenameIndex(
            model_name='doctor',
            new_name='doctors_doc_hospita_4ecc99_idx',
            old_name='doctors_doc_hospita_a2834b_idx',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='verified_by',
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='doctors_doc_is_avai_e473c5_idx'),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
