# Generated by Django 6.0 on 2026-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='time_slots',
            field=models.JSONField(blank=True, default=list, help_text='Auto-calculated appointment time slots'),
        ),
    ]
