# Generated by Django 5.1.2 on 2026-03-26 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_doctorschedule_time_slots'),
        ('hospitals', '0003_remove_hospitaldepartment_available_beds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(help_text='Primary hospital', on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(help_text='User account for this doctor', limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
