# Generated by Django 5.1.2 on 2026-04-07 08:06

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_patientappointment_is_follow_up'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('diagnosis', models.TextField(help_text='Diagnosis and clinical findings')),
                ('notes', models.TextField(blank=True, help_text='Additional consultation notes', null=True)),
                ('appointment', models.OneToOneField(help_text='Appointment linked to this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_record', to='patients.patientappointment')),
                ('created_by', models.ForeignKey(help_text='User who created this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('frequency', models.CharField(help_text='e.g. 2 times a day', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 5 days', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this medicine', null=True)),
                ('created_by', models.ForeignKey(help_text='User who created this medicine entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this medicine belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='appointments.prescription')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
