# Generated by Django 5.1.2 on 2026-04-14 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this medicine entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(help_text='Appointment linked to this prescription', on_delete=django.db.models.deletion.CASCADE, related_name='prescription_record', to='patients.patientappointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this prescription', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(help_text='Prescription this medicine belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='appointments.prescription'),
        ),
    ]
