# Generated by Django 5.1.2 on 2026-04-14 06:40

import cloudinary.models
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Hospital name', max_length=200)),
                ('registration_number', models.CharField(help_text='Hospital registration/license number', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Hospital contact email', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Hospital contact phone', max_length=32)),
                ('address', models.TextField(help_text='Hospital physical address')),
                ('city', models.CharField(help_text='City where hospital is located', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Nepal', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Hospital description and facilities', null=True)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('website', models.URLField(blank=True, help_text='Hospital website URL', null=True)),
                ('established_date', models.DateField(blank=True, help_text='Date when hospital was established', null=True)),
                ('total_beds', models.PositiveIntegerField(default=0, help_text='Total number of beds')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=32, null=True)),
                ('khalti_secret_key', models.CharField(blank=True, help_text='Khalti secret key for payment processing', max_length=255, null=True)),
                ('khalti_public_key', models.CharField(blank=True, help_text='Khalti public key for payment processing', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether hospital is verified by super admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when hospital was verified', null=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hospital Admin',
                'verbose_name_plural': 'Hospital Admins',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Department name (e.g., Cardiology, Orthopedics)', max_length=100)),
                ('code', models.CharField(help_text='Department code', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
            ],
            options={
                'verbose_name': 'Hospital Department',
                'verbose_name_plural': 'Hospital Departments',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hospital Staff',
                'verbose_name_plural': 'Hospital Staff',
                'ordering': ['-created'],
            },
        ),
    ]
