# Generated by Django 5.1.2 on 2026-01-11 07:30

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Hospital name', max_length=200)),
                ('registration_number', models.CharField(help_text='Hospital registration/license number', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='Hospital contact email', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Hospital contact phone', max_length=15)),
                ('address', models.TextField(help_text='Hospital physical address')),
                ('city', models.CharField(help_text='City where hospital is located', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Nepal', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Hospital description and facilities', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Hospital logo', null=True, upload_to='hospitals/logos/')),
                ('website', models.URLField(blank=True, help_text='Hospital website URL', null=True)),
                ('established_date', models.DateField(blank=True, help_text='Date when hospital was established', null=True)),
                ('total_beds', models.PositiveIntegerField(default=0, help_text='Total number of beds')),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact number', max_length=15, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether hospital is verified by super admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when hospital was verified', null=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Super admin who verified this hospital', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hospitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.CharField(help_text='Admin designation/title', max_length=100)),
                ('employee_id', models.CharField(help_text='Employee ID', max_length=50, unique=True)),
                ('department', models.CharField(blank=True, help_text='Department', max_length=100, null=True)),
                ('joining_date', models.DateField(help_text='Date when admin joined')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions for this admin')),
                ('hospital', models.ForeignKey(help_text='Hospital managed by this admin', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='hospitals.hospital')),
                ('user', models.OneToOneField(help_text='User account for this admin', limit_choices_to={'user_type': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Admin',
                'verbose_name_plural': 'Hospital Admins',
                'ordering': ['-joining_date'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Department name (e.g., Cardiology, Orthopedics)', max_length=100)),
                ('code', models.CharField(help_text='Department code', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Department description', null=True)),
                ('total_beds', models.PositiveIntegerField(default=0, help_text='Total beds in this department')),
                ('available_beds', models.PositiveIntegerField(default=0, help_text='Currently available beds')),
                ('head_doctor', models.ForeignKey(blank=True, help_text='Head doctor of this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(help_text='Hospital this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital')),
            ],
            options={
                'verbose_name': 'Hospital Department',
                'verbose_name_plural': 'Hospital Departments',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city', 'state'], name='hospitals_h_city_7b2c17_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_verified', 'is_active'], name='hospitals_h_is_veri_7c5068_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitaldepartment',
            unique_together={('hospital', 'code')},
        ),
    ]
