# Generated by Django 5.1.2 on 2026-03-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaladmin',
            options={'ordering': ['-created'], 'verbose_name': 'Hospital Admin', 'verbose_name_plural': 'Hospital Admins'},
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='department',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='permissions',
        ),
    ]
