# Generated by Django 5.1.2 on 2026-04-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Super admin who verified this hospital', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hospitals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital managed by this admin', on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='hospitaladmin',
            name='user',
            field=models.OneToOneField(help_text='User account for this admin', limit_choices_to={'user_type': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitaldepartment',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital this department belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital where this staff member works', on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='hospitalstaff',
            name='user',
            field=models.OneToOneField(help_text='User account for this staff member', limit_choices_to={'user_type__in': ['STAFF', 'LAB_ASSISTANT', 'PHARMACIST']}, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['city', 'state'], name='hospitals_h_city_7b2c17_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_verified', 'is_active'], name='hospitals_h_is_veri_7c5068_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='hospitaldepartment',
            unique_together={('hospital', 'code')},
        ),
    ]
