# Generated by Django 6.0 on 2026-04-01 11:13

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='khalti_public_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Khalti public key for payment processing', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='khalti_secret_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Khalti secret key for payment processing', null=True),
        ),
    ]
