# Generated by Django 6.0 on 2026-03-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldepartment',
            name='available_beds',
        ),
        migrations.RemoveField(
            model_name='hospitaldepartment',
            name='head_doctor',
        ),
        migrations.RemoveField(
            model_name='hospitaldepartment',
            name='total_beds',
        ),
    ]
