# Generated by Django 6.0 on 2026-03-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_alter_hospitaladmin_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='hospitaladmin',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='hospitaldepartment',
            name='is_removed',
        ),
    ]
