# Generated by Django 5.1.2 on 2026-03-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_remove_hospitaldepartment_available_beds_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaff',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital where this staff member works', on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='hospitals.hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalstaff',
            name='user',
            field=models.OneToOneField(help_text='User account for this staff member', limit_choices_to={'user_type__in': ['STAFF', 'LAB_ASSISTANT', 'PHARMACIST']}, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
