# Generated by Django 5.1.2 on 2026-04-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_disable_khalti_field_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Emergency contact number', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.CharField(help_text='Hospital contact phone', max_length=32),
        ),
    ]
